# Generated by ChatGPT on 2026-02-16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]

