# Generated by Django 5.2 on 2025-06-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_cancel_mailing", "Can cancel mailing"),
                    ("can_see_all_mailings", "Can see all mailings"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
